#!/bin/bash

# Verifies an unverified and vice versa report in an Ushahidi deployment via the api.
#
# This requires the command line curl app installed.
#
# Author: Henry Addo <henry@ushahidi.com>"

curl -v -u 'admin:admin' -F 'task=reports' \
-F 'action=verify' \
-F 'incident_id=1' \
'http://localhost/ush/api'
