#!/bin/bash

# Fetches reports in an ushahidi deployment by unapproved via the api.
# It returns all unapproved reports.
# This requires the command line curl app installed.
#
# Author: Henry Addo <henry@ushahidi.com>"

curl -v -u 'admin:admin' -F 'task=reports' \
-F 'by=unapproved' \
'http://demo.ushahidi.com/api'
