#!/bin/bash

# Approves a comment in an ushahidi deployment via the api
# This requires the command line curl app installed
# Author: Henry Addo <henry@ushahidi.com>"

curl -v -u 'admin:admin' -F 'task=comments' \
-F 'action=approve' \
-F 'comment_id=1' \
'http://demo.ushahidi.com/api'
