#!/bin/bash

# Edits an existing category in an Ushahidi deployment
#
# This requires the command line curl app installed
# Author: Henry Addo <henry@ushahidi.com>"

curl -v -u 'admin:admin' -F 'task=category' \
-F 'action=edit' \
-F 'category_title=Test+api+category+title+editted' \
-F 'category_description=Testing+with+the+api+editted' \
-F 'category_id=5' \
-F 'parent_id=0' \
-F 'category_color=ff0000' \
'http://demo.ushahidi.com/api'
