#!/bin/bash

# Approves a report in an ushahidi deployment via the api
# This requires the command line curl app installed
# Author: Henry Addo <henry@ushahidi.com>"

curl -v -u 'admin:admin' -F 'task=reports' \
-F 'action=approve' \
-F 'incident_id=1' \
'http://demo.ushahidi.com/api'
