#!/bin/bash

# Adds new comment to an ushahidi deployment via the api
# This requires the command line curl app installed
# Author: Henry Addo <henry@ushahidi.com>"

curl -v -u 'admin:admin' -F 'task=comments' \
-F 'action=add' \
-F 'incident_id=1' \
-F 'comment_author=Henry Addo' \
-F 'comment_description=Passing comment via the api' \
-F 'comment_email=henry@ushahidi.com' \
'http://demo.ushahidi.com/api'
